services:
  observer:
    container_name: observer
    image: tgbots-observer:local
    depends_on:
      - nats
    ports:
      - "8001:8001"
    environment:
      DEBUG: true
      HTTP_PORT: 8001
      NATS_URL: "nats://nats:4222"

  nats:
    container_name: nats
    image: nats
    command: -js -m 8222
    ports:
      - "8222:8222"
      - "4222:4222"
